version: "3.8"
services:
  envoy:
    build: _devel/envoy/
    container_name: envoy
    command: "/usr/local/bin/envoy -c /etc/envoy/envoy.yaml --log-path /tmp/system.log --log-format '[SYSTEM][%Y-%m-%d %T.%e][%t][%l][%n] %v'"
    ports:
      - "8081:80"
      - "9901:9901"
    volumes:
      - ./files/publickey-jwks.txt:/etc/envoy/jwks/publickey-jwks.txt
      - ./_devel/envoy/envoy.yaml:/etc/envoy/envoy.yaml
      - go_logs:/app/logs

  service:
    build: service/
    container_name: service
    ports:
      - "30001:30001"
    volumes:
      - ./files/privatekey.pem:/files/privatekey.pem
      - ./files/publickey.pem:/files/publickey.pem

volumes:
  go_logs: