### Create token
POST http://localhost:8081/v1/jwt-tokens

> {%
client.global.set("token", response.body.token);
 %}

### Verify token
GET http://localhost:8081/v1/jwt-tokens
Authorization: Bearer {{token}}

### Show Self
GET http://localhost:8081/v1/self
foo: foo
bar: bar

### Error, not bearer
GET http://localhost:8081/v1/jwt-tokens
Authorization: Bad

### Error, bad token
GET http://localhost:8081/v1/jwt-tokens
Authorization: Bearer bad

### Error, no authorization
GET http://localhost:8081/v1/jwt-tokens
